# Generated by Django 5.2.5 on 2025-08-26 02:27

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "model_name",
                    models.CharField(
                        help_text="LLM model to use (e.g., 'gpt-4', 'gpt-3.5-turbo')",
                        max_length=100,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        help_text="API key for LLM service", max_length=255
                    ),
                ),
                (
                    "base_prompt",
                    models.TextField(help_text="Base prompt template for AI tutor"),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
                ("max_tokens", models.PositiveIntegerField(default=1000)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "llm_config",
            },
        ),
    ]
