# Generated by Django 5.2.5 on 2025-09-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="llmconfig",
            old_name="max_tokens",
            new_name="max_completion_tokens",
        ),
    ]
