name: llteacher
runtime:
  name: nodejs
  options:
    packagemanager: npm
description: LLTeacher AWS App Runner and PostgreSQL infrastructure
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
